apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/managed-by: kargo
    app.kubernetes.io/part-of: infrastructure
    environment: dev
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.14.4
  name: cert-manager
  namespace: cert-manager
