apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/managed-by: kargo
    app.kubernetes.io/part-of: infrastructure
    environment: staging
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.14.4
  name: cert-manager-cainjector
  namespace: cert-manager
