apiVersion: v1
kind: Service
metadata:
  name: kustomize-nginx
  namespace: nginx-staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx
  type: ClusterIP
