apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: cert-manager-staging
  namespace: argocd-example-apps
spec:
  # Assign this Stage to the staging cluster controller
  shard: staging-shard
  requestedFreight:
  - origin:
      kind: Warehouse
      name: cert-manager
    sources:
      stages:
      - cert-manager-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: repoURL
          value: https://github.com/recmanj/argocd-example-apps.git
        - name: branch
          value: master
        - name: env
          value: staging
        - name: image
          value: quay.io/jetstack/cert-manager-controller
        - name: appPath
          value: _apps/cert-manager
        - name: appName
          value: cert-manager
