apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-staging
  namespace: argocd-example-apps
spec:
  # Assign this Stage to the staging cluster controller
  shard: staging-shard
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages:
      - nginx-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: repoURL
          value: https://github.com/recmanj/argocd-example-apps.git
        - name: branch
          value: master
        - name: env
          value: staging
        - name: image
          value: public.ecr.aws/nginx/nginx
        - name: appPath
          value: apps/nginx
        - name: appName
          value: nginx
