apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: nginx-dev
  namespace: argocd-example-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: repoURL
          value: https://github.com/recmanj/argocd-example-apps.git
        - name: branch
          value: master
        - name: env
          value: dev
        - name: image
          value: nginx
        - name: appPath
          value: _apps/nginx
        - name: appName
          value: nginx
